name: intership
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.2
  gap: ^3.0.1
  hive: ^2.2.3
  supabase_flutter: ^2.3.4
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  equatable: ^2.0.5
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  formz: ^0.6.0
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0
  local_auth: ^2.2.0
  mobile_scanner: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
